# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/erik/Documents/school/PNTalk_Virtual-machine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/erik/Documents/school/PNTalk_Virtual-machine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/erik/Documents/school/PNTalk_Virtual-machine/CMakeFiles /home/erik/Documents/school/PNTalk_Virtual-machine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/erik/Documents/school/PNTalk_Virtual-machine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Translator2

# Build rule for target.
Translator2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Translator2
.PHONY : Translator2

# fast build rule for target.
Translator2/fast:
	$(MAKE) -f CMakeFiles/Translator2.dir/build.make CMakeFiles/Translator2.dir/build
.PHONY : Translator2/fast

#=============================================================================
# Target rules for targets named VM2

# Build rule for target.
VM2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 VM2
.PHONY : VM2

# fast build rule for target.
VM2/fast:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/build
.PHONY : VM2/fast

Translator/src/error.o: Translator/src/error.cpp.o

.PHONY : Translator/src/error.o

# target to build an object file
Translator/src/error.cpp.o:
	$(MAKE) -f CMakeFiles/Translator2.dir/build.make CMakeFiles/Translator2.dir/Translator/src/error.cpp.o
.PHONY : Translator/src/error.cpp.o

Translator/src/error.i: Translator/src/error.cpp.i

.PHONY : Translator/src/error.i

# target to preprocess a source file
Translator/src/error.cpp.i:
	$(MAKE) -f CMakeFiles/Translator2.dir/build.make CMakeFiles/Translator2.dir/Translator/src/error.cpp.i
.PHONY : Translator/src/error.cpp.i

Translator/src/error.s: Translator/src/error.cpp.s

.PHONY : Translator/src/error.s

# target to generate assembly for a file
Translator/src/error.cpp.s:
	$(MAKE) -f CMakeFiles/Translator2.dir/build.make CMakeFiles/Translator2.dir/Translator/src/error.cpp.s
.PHONY : Translator/src/error.cpp.s

Translator/src/lexAnalyzator.o: Translator/src/lexAnalyzator.cpp.o

.PHONY : Translator/src/lexAnalyzator.o

# target to build an object file
Translator/src/lexAnalyzator.cpp.o:
	$(MAKE) -f CMakeFiles/Translator2.dir/build.make CMakeFiles/Translator2.dir/Translator/src/lexAnalyzator.cpp.o
.PHONY : Translator/src/lexAnalyzator.cpp.o

Translator/src/lexAnalyzator.i: Translator/src/lexAnalyzator.cpp.i

.PHONY : Translator/src/lexAnalyzator.i

# target to preprocess a source file
Translator/src/lexAnalyzator.cpp.i:
	$(MAKE) -f CMakeFiles/Translator2.dir/build.make CMakeFiles/Translator2.dir/Translator/src/lexAnalyzator.cpp.i
.PHONY : Translator/src/lexAnalyzator.cpp.i

Translator/src/lexAnalyzator.s: Translator/src/lexAnalyzator.cpp.s

.PHONY : Translator/src/lexAnalyzator.s

# target to generate assembly for a file
Translator/src/lexAnalyzator.cpp.s:
	$(MAKE) -f CMakeFiles/Translator2.dir/build.make CMakeFiles/Translator2.dir/Translator/src/lexAnalyzator.cpp.s
.PHONY : Translator/src/lexAnalyzator.cpp.s

Translator/src/main.o: Translator/src/main.cpp.o

.PHONY : Translator/src/main.o

# target to build an object file
Translator/src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Translator2.dir/build.make CMakeFiles/Translator2.dir/Translator/src/main.cpp.o
.PHONY : Translator/src/main.cpp.o

Translator/src/main.i: Translator/src/main.cpp.i

.PHONY : Translator/src/main.i

# target to preprocess a source file
Translator/src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Translator2.dir/build.make CMakeFiles/Translator2.dir/Translator/src/main.cpp.i
.PHONY : Translator/src/main.cpp.i

Translator/src/main.s: Translator/src/main.cpp.s

.PHONY : Translator/src/main.s

# target to generate assembly for a file
Translator/src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Translator2.dir/build.make CMakeFiles/Translator2.dir/Translator/src/main.cpp.s
.PHONY : Translator/src/main.cpp.s

Translator/src/parse.o: Translator/src/parse.cpp.o

.PHONY : Translator/src/parse.o

# target to build an object file
Translator/src/parse.cpp.o:
	$(MAKE) -f CMakeFiles/Translator2.dir/build.make CMakeFiles/Translator2.dir/Translator/src/parse.cpp.o
.PHONY : Translator/src/parse.cpp.o

Translator/src/parse.i: Translator/src/parse.cpp.i

.PHONY : Translator/src/parse.i

# target to preprocess a source file
Translator/src/parse.cpp.i:
	$(MAKE) -f CMakeFiles/Translator2.dir/build.make CMakeFiles/Translator2.dir/Translator/src/parse.cpp.i
.PHONY : Translator/src/parse.cpp.i

Translator/src/parse.s: Translator/src/parse.cpp.s

.PHONY : Translator/src/parse.s

# target to generate assembly for a file
Translator/src/parse.cpp.s:
	$(MAKE) -f CMakeFiles/Translator2.dir/build.make CMakeFiles/Translator2.dir/Translator/src/parse.cpp.s
.PHONY : Translator/src/parse.cpp.s

Translator/src/semantic.o: Translator/src/semantic.cpp.o

.PHONY : Translator/src/semantic.o

# target to build an object file
Translator/src/semantic.cpp.o:
	$(MAKE) -f CMakeFiles/Translator2.dir/build.make CMakeFiles/Translator2.dir/Translator/src/semantic.cpp.o
.PHONY : Translator/src/semantic.cpp.o

Translator/src/semantic.i: Translator/src/semantic.cpp.i

.PHONY : Translator/src/semantic.i

# target to preprocess a source file
Translator/src/semantic.cpp.i:
	$(MAKE) -f CMakeFiles/Translator2.dir/build.make CMakeFiles/Translator2.dir/Translator/src/semantic.cpp.i
.PHONY : Translator/src/semantic.cpp.i

Translator/src/semantic.s: Translator/src/semantic.cpp.s

.PHONY : Translator/src/semantic.s

# target to generate assembly for a file
Translator/src/semantic.cpp.s:
	$(MAKE) -f CMakeFiles/Translator2.dir/build.make CMakeFiles/Translator2.dir/Translator/src/semantic.cpp.s
.PHONY : Translator/src/semantic.cpp.s

VM/src/error.o: VM/src/error.cpp.o

.PHONY : VM/src/error.o

# target to build an object file
VM/src/error.cpp.o:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/error.cpp.o
.PHONY : VM/src/error.cpp.o

VM/src/error.i: VM/src/error.cpp.i

.PHONY : VM/src/error.i

# target to preprocess a source file
VM/src/error.cpp.i:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/error.cpp.i
.PHONY : VM/src/error.cpp.i

VM/src/error.s: VM/src/error.cpp.s

.PHONY : VM/src/error.s

# target to generate assembly for a file
VM/src/error.cpp.s:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/error.cpp.s
.PHONY : VM/src/error.cpp.s

VM/src/instance.o: VM/src/instance.cpp.o

.PHONY : VM/src/instance.o

# target to build an object file
VM/src/instance.cpp.o:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/instance.cpp.o
.PHONY : VM/src/instance.cpp.o

VM/src/instance.i: VM/src/instance.cpp.i

.PHONY : VM/src/instance.i

# target to preprocess a source file
VM/src/instance.cpp.i:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/instance.cpp.i
.PHONY : VM/src/instance.cpp.i

VM/src/instance.s: VM/src/instance.cpp.s

.PHONY : VM/src/instance.s

# target to generate assembly for a file
VM/src/instance.cpp.s:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/instance.cpp.s
.PHONY : VM/src/instance.cpp.s

VM/src/main.o: VM/src/main.cpp.o

.PHONY : VM/src/main.o

# target to build an object file
VM/src/main.cpp.o:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/main.cpp.o
.PHONY : VM/src/main.cpp.o

VM/src/main.i: VM/src/main.cpp.i

.PHONY : VM/src/main.i

# target to preprocess a source file
VM/src/main.cpp.i:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/main.cpp.i
.PHONY : VM/src/main.cpp.i

VM/src/main.s: VM/src/main.cpp.s

.PHONY : VM/src/main.s

# target to generate assembly for a file
VM/src/main.cpp.s:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/main.cpp.s
.PHONY : VM/src/main.cpp.s

VM/src/method.o: VM/src/method.cpp.o

.PHONY : VM/src/method.o

# target to build an object file
VM/src/method.cpp.o:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/method.cpp.o
.PHONY : VM/src/method.cpp.o

VM/src/method.i: VM/src/method.cpp.i

.PHONY : VM/src/method.i

# target to preprocess a source file
VM/src/method.cpp.i:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/method.cpp.i
.PHONY : VM/src/method.cpp.i

VM/src/method.s: VM/src/method.cpp.s

.PHONY : VM/src/method.s

# target to generate assembly for a file
VM/src/method.cpp.s:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/method.cpp.s
.PHONY : VM/src/method.cpp.s

VM/src/object.o: VM/src/object.cpp.o

.PHONY : VM/src/object.o

# target to build an object file
VM/src/object.cpp.o:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/object.cpp.o
.PHONY : VM/src/object.cpp.o

VM/src/object.i: VM/src/object.cpp.i

.PHONY : VM/src/object.i

# target to preprocess a source file
VM/src/object.cpp.i:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/object.cpp.i
.PHONY : VM/src/object.cpp.i

VM/src/object.s: VM/src/object.cpp.s

.PHONY : VM/src/object.s

# target to generate assembly for a file
VM/src/object.cpp.s:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/object.cpp.s
.PHONY : VM/src/object.cpp.s

VM/src/outputgen.o: VM/src/outputgen.cpp.o

.PHONY : VM/src/outputgen.o

# target to build an object file
VM/src/outputgen.cpp.o:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/outputgen.cpp.o
.PHONY : VM/src/outputgen.cpp.o

VM/src/outputgen.i: VM/src/outputgen.cpp.i

.PHONY : VM/src/outputgen.i

# target to preprocess a source file
VM/src/outputgen.cpp.i:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/outputgen.cpp.i
.PHONY : VM/src/outputgen.cpp.i

VM/src/outputgen.s: VM/src/outputgen.cpp.s

.PHONY : VM/src/outputgen.s

# target to generate assembly for a file
VM/src/outputgen.cpp.s:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/outputgen.cpp.s
.PHONY : VM/src/outputgen.cpp.s

VM/src/place.o: VM/src/place.cpp.o

.PHONY : VM/src/place.o

# target to build an object file
VM/src/place.cpp.o:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/place.cpp.o
.PHONY : VM/src/place.cpp.o

VM/src/place.i: VM/src/place.cpp.i

.PHONY : VM/src/place.i

# target to preprocess a source file
VM/src/place.cpp.i:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/place.cpp.i
.PHONY : VM/src/place.cpp.i

VM/src/place.s: VM/src/place.cpp.s

.PHONY : VM/src/place.s

# target to generate assembly for a file
VM/src/place.cpp.s:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/place.cpp.s
.PHONY : VM/src/place.cpp.s

VM/src/trans.o: VM/src/trans.cpp.o

.PHONY : VM/src/trans.o

# target to build an object file
VM/src/trans.cpp.o:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/trans.cpp.o
.PHONY : VM/src/trans.cpp.o

VM/src/trans.i: VM/src/trans.cpp.i

.PHONY : VM/src/trans.i

# target to preprocess a source file
VM/src/trans.cpp.i:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/trans.cpp.i
.PHONY : VM/src/trans.cpp.i

VM/src/trans.s: VM/src/trans.cpp.s

.PHONY : VM/src/trans.s

# target to generate assembly for a file
VM/src/trans.cpp.s:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/trans.cpp.s
.PHONY : VM/src/trans.cpp.s

VM/src/vm.o: VM/src/vm.cpp.o

.PHONY : VM/src/vm.o

# target to build an object file
VM/src/vm.cpp.o:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/vm.cpp.o
.PHONY : VM/src/vm.cpp.o

VM/src/vm.i: VM/src/vm.cpp.i

.PHONY : VM/src/vm.i

# target to preprocess a source file
VM/src/vm.cpp.i:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/vm.cpp.i
.PHONY : VM/src/vm.cpp.i

VM/src/vm.s: VM/src/vm.cpp.s

.PHONY : VM/src/vm.s

# target to generate assembly for a file
VM/src/vm.cpp.s:
	$(MAKE) -f CMakeFiles/VM2.dir/build.make CMakeFiles/VM2.dir/VM/src/vm.cpp.s
.PHONY : VM/src/vm.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Translator2"
	@echo "... VM2"
	@echo "... Translator/src/error.o"
	@echo "... Translator/src/error.i"
	@echo "... Translator/src/error.s"
	@echo "... Translator/src/lexAnalyzator.o"
	@echo "... Translator/src/lexAnalyzator.i"
	@echo "... Translator/src/lexAnalyzator.s"
	@echo "... Translator/src/main.o"
	@echo "... Translator/src/main.i"
	@echo "... Translator/src/main.s"
	@echo "... Translator/src/parse.o"
	@echo "... Translator/src/parse.i"
	@echo "... Translator/src/parse.s"
	@echo "... Translator/src/semantic.o"
	@echo "... Translator/src/semantic.i"
	@echo "... Translator/src/semantic.s"
	@echo "... VM/src/error.o"
	@echo "... VM/src/error.i"
	@echo "... VM/src/error.s"
	@echo "... VM/src/instance.o"
	@echo "... VM/src/instance.i"
	@echo "... VM/src/instance.s"
	@echo "... VM/src/main.o"
	@echo "... VM/src/main.i"
	@echo "... VM/src/main.s"
	@echo "... VM/src/method.o"
	@echo "... VM/src/method.i"
	@echo "... VM/src/method.s"
	@echo "... VM/src/object.o"
	@echo "... VM/src/object.i"
	@echo "... VM/src/object.s"
	@echo "... VM/src/outputgen.o"
	@echo "... VM/src/outputgen.i"
	@echo "... VM/src/outputgen.s"
	@echo "... VM/src/place.o"
	@echo "... VM/src/place.i"
	@echo "... VM/src/place.s"
	@echo "... VM/src/trans.o"
	@echo "... VM/src/trans.i"
	@echo "... VM/src/trans.s"
	@echo "... VM/src/vm.o"
	@echo "... VM/src/vm.i"
	@echo "... VM/src/vm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

